import {
  OpenAPIRegistry,
  OpenApiGeneratorV31,
  extendZodWithOpenApi,
} from '@asteasolutions/zod-to-openapi';

import {z} from 'zod';

extendZodWithOpenApi(z);

export const registry = new OpenAPIRegistry();

export function generateOpenAPI(url = 'http://localhost:3000') {
  registry.registerPath({
    method: 'get',
    path: '/api/hello',
    summary: 'Hello World Test Endpoint',
    responses: {
      200: {
        description: 'Successful response',
        content: {
          'application/json': {
            schema: z.object({}),
          },
        },
      },
    },
  });

  const config = {
    openapi: '3.1.0',
    info: {
      version: '1.0.0',
      title: 'Vacso frameworkBackend',
      description: 'API generated by Vacso frameworkBackend',
    },
    servers: [{url}],
  };

  return new OpenApiGeneratorV31(registry.definitions).generateDocument(config);
}
